### ISSUE TITLE
Pod Point CT reading output

### ISSUE THREAD

**Issue by adyoull** [mattrayner/pod-point-home-assistant-component#11]
Hi Matt

Is there anyway to get the output from the CT the pod point uses for Load limiting? As this reports back to pod point according to their documentation and privacy agreement, and is also used as part of CarbonSync for national grid.

As this would be a great addition for real-time property load detailing.

**Comment by mattrayner** [comment]
Hi @adyoull, unfortunately this information is not currently available through their public facing APIs so is not something I can add to the system at this time even though it's a great addition.

Personally I use a Shelly monitor with two clamps connected, one on the house and one on the positive line to the pod. This allows me to monitor both the overall house usage and the usage of the pod itself (separately from the less accurate stats provided via the API). Hope this helps :)
