### ISSUE TITLE
New Feature request - add cost of last charge

### ISSUE THREAD

**Issue by jimmyeao** [mattrayner/pod-point-home-assistant-component#12]
As the title says :) would be nice to be able to track this.

**Comment by mattrayner** [comment]
Thanks for requesting, I have added this and included it in [4.0.2](https://github.com/mattrayner/pod-point-home-assistant-component/releases/tag/0.4.2). Let me know if you have any additional questions or feedback.

I'd recommend looking at the [Cost Sensors](https://github.com/mattrayner/pod-point-home-assistant-component#cost-sensors) section of the README as there are some caveats.
