### ISSUE TITLE
Integration is using deprecated `DEVICE_CLASS_*` constants

### ISSUE THREAD

**Issue by frenck** [mattrayner/pod-point-home-assistant-component#14]
## Version of the custom_component

All

## Configuration

```yaml

n/a

```

## Describe the bug

This custom integration uses deprecated `DEVICE_CLASS_*` constants in its codebase.

The `DEVICE_CLASS_*` constants have been deprecated and replaced in Home Assistant Core 2021.12 (over a year ago). I would highly suggest updating/migrating this integration to the new enums.

For example, for the device classes supported by the `sensor` platform, there is now a `SensorDeviceClass` enum. So if a sensor previously used the `DEVICE_CLASS_ENERGY` constant, it should now use `SensorDeviceClass.ENERGY`. Other platforms (like `binary_sensor`, and `number`) provide similar enumerations for their supported device classes.

The migration thus only consists of replacing constants with an enumeration member and is, therefore, very low impact and should be fairly straightforward.

If I can help resolve any questions regarding this change or migration, feel free to ask or respond to this issue. I'm happy to help!

Kindest regards,

../Frenck

## Debug log

```text

n/a

```

**Comment by frenck** [comment]
Thanks for a record-time response on this one @mattrayner 🚀 

Happy New Year 🥂 

../Frenck

**Comment by mattrayner** [comment]
As you said, it was s SUPER easy fix, interestingly I couldn't find any mention in the documentation of the 'right' way to do this, but then I also couldn't find any mention of the `DEVICE_CLASS_*` way either. I might contribute an update on this one!

Happy New Year to you too!! 🥂

**Comment by mattrayner** [comment]
I've opened a PR for the developer docs to add a tip for `Cover`, `Sensor` and `Binary Sensor`. Informing devs to use the DeviceClass enums https://github.com/home-assistant/developers.home-assistant/pull/1611
