### ISSUE TITLE
PodPoint didn’t load on 2022.12.6

### ISSUE THREAD

**Issue by i-am-shodan** [mattrayner/pod-point-home-assistant-component#21]
Upgraded HASS to 2022.12.6. HACS says podpoint hasn’t loaded.

HASS log

Logger: homeassistant.setup
Source: setup.py:338 
First occurred: 15:24:15 (1 occurrences) 
Last logged: 15:24:15

Unable to prepare setup for platform pod_point.sensor: Platform not found (cannot import name 'UnitOfTime' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).

**Comment by mattrayner** [comment]
HI @i-am-shodan, It looks like I've used a new feature in Home Assistant, I'll look at either locking the 'compatible with' to 2023.1, or I'll see what the 'old' alternative is.

Feels weird saying old for a month ago :D

**Comment by mattrayner** [comment]
Yep, looks like I'm a trailblazer, the 'old' way of doing this is depreciates for UnitOfTime.

https://github.com/home-assistant/core/pull/83288

As the older way is now depreciated I don't want to add in deprecated code so the solution here will likely be to either roll back to 0.4 on the integration, or upgrade to 2023.1

Sorry I don't have a more compatible answer 👎

**Comment by mattrayner** [comment]
I've cut a new release `1.0.2` which explicitly calls out the change to `hacs.json` and requirement for `>2023.1.0`.

Thanks again for raising!

**Comment by i-am-shodan** [comment]
Didn’t release I wasn’t on latest. Have upgraded. Thanks for checking this out.
