### ISSUE TITLE
Status Incorrect if using Charge Now in new Pod Point App

### ISSUE THREAD

**Issue by adyoull** [mattrayner/pod-point-home-assistant-component#25]
Status shows as: "Connected but waiting for schedule" if you use charge now, which allows you to bypass the charge schedule to instant charging, without disabling a schedule.

Attachments showing, Power being pulled, Charge being passed, and status from Integration.

![Screenshot 2023-04-26 at 17 35 11](https://user-images.githubusercontent.com/39759856/234643275-28ca8ab3-1870-4fe1-bdbc-271d27dd2471.png)
![234643782-4155bea3-5982-4c49-9039-f6fdf834dd28](https://user-images.githubusercontent.com/39759856/234672495-aa63623e-07a2-4bf4-bc30-3b9ff0d27efb.png)
![234643805-f45ef6d5-86d9-4b7c-b451-6f9b31d3eb5e](https://user-images.githubusercontent.com/39759856/234672501-f76f44fc-35d4-41a2-a596-124dc322e0cc.png)
![234643832-cc7f80b0-9c33-41db-9c3f-f2920e4e2bd2](https://user-images.githubusercontent.com/39759856/234672503-8bb16a54-9dba-4d1e-af28-ebd5f578b89b.png)

**Comment by mattrayner** [comment]
Thanks for reporting, I'm in the process of adding support for charge overrides (Pod Point's name for the charge now functionality) and am hoping to have a new version in around a week

**Comment by mattrayner** [comment]
I've just shipped a new version 1.2.0 which includes a service which you can use to set a charge now session too
