### ISSUE TITLE
Total energy keeps incrementing

### ISSUE THREAD

**Issue by Murleen** [mattrayner/pod-point-home-assistant-component#3]
## Version of the custom_component
0.3.0-beta2

## Configuration

Using a Pod Point Solo charger

## Describe the bug

Every 5 minutes I see the "total energy" sensor increment by the total energy amount (e.g. if the reported total energy was 500 kWh, then I see 500, then 5min later 1000, then 1500 etc)

**Comment by FileGo** [comment]
Same issue here.

**Comment by mattrayner** [comment]
This has now been fixes in 3.0-beta4. Please update and let me know how you get on :)
