### ISSUE TITLE
Frequency of polling

### ISSUE THREAD

**Issue by sjhowl** [mattrayner/pod-point-home-assistant-component#43]
Hi

How frequently does this poll the podpoint to see if a status has changed and can this be increased to more frequently?  I'm particularly interested in if the cable is plugged in or unplugged.  It appears to check approximately every five minutes.  This may however be podpoint doing this and not the integration.

Stewart

**Comment by mattrayner** [comment]
Hi Stewart, the default is 5 minutes, this is a polling rate set on the client side.

Its set to ensure that we don't over-burden the pod-point systems (especially as multiple people have the plugin installed).

You can however override this buy clicking 'Configure' within the Home Assistant UI and changing the polling interval:
<img width="427" alt="image" src="https://github.com/mattrayner/pod-point-home-assistant-component/assets/3502902/ab2f5752-62c4-4efc-8cf3-a4f4ec67668e">

Please bear in mind that setting this to a low number could cause Pod Point to reach out/disable your access/actively try to stop the plugin from working

**Comment by sjhowl** [comment]
Thanks Matt,  that's really useful information.

**Comment by sjhowl** [comment]
I changed the time to 120 from 300 and now it's stopped working.  I'm guessing Pod Point have disabled my access.  I've put it back to 300 but now I don't know if this will restore the service, if I need to reinstall the integration or if I now need to contact Pod Point.

**Comment by mattrayner** [comment]
Does your app access still work? Try loggingg out and back in on the app

If not then you will need to reach out to Pod Point

**Comment by sjhowl** [comment]
Hi Matt

I’ve done all of this now. I called Pod Point, and they have messaged their data team.  I logged out of the app and when I logged back in again the stored password on my phone didn’t work so I reset that and I’m back in the app.  I then deleted the integration and re-installed it and it’s now all working again.  I’ve therefore unsure which part of this fixed it but it’s fixed.  Thanks again for all your help.

Kind regards

Stewart

From: Matt Rayner ***@***.***>
Reply to: mattrayner/pod-point-home-assistant-component ***@***.***>
Date: Thursday, 14 September 2023 at 10:57
To: mattrayner/pod-point-home-assistant-component ***@***.***>
Cc: Stewart Howl ***@***.***>, Author ***@***.***>
Subject: Re: [mattrayner/pod-point-home-assistant-component] Frequency of polling (Issue #43)

Does your app access still work? Try loggingg out and back in on the app

If not then you will need to reach out to Pod Point
