### ISSUE TITLE
Stop Charge Now - Clearer/cleaner way to cancel a schedule override

### ISSUE THREAD

**Issue by busywait** [mattrayner/pod-point-home-assistant-component#50]
**Is your feature request related to a problem? Please describe.**

I want to be able to cancel any schedule override that might be set on my Pod Point, which I might have started using the Charge Now button on the Pod Point app or the Charge Now service in the HA integration.

**Describe the solution you'd like**

I'd like an extra service, "Stop Charge Now" named like the Pod Point app button; or allow 0 seconds in the Charge Now service call.

Or mention in the documentation what the recommended way to cancel a schedule override is.

**Describe alternatives you've considered**

Configuring a 5 second override to overwite anything that might be running.

`
if:
  - condition: state
    entity_id: sensor.psl_166021_charge_override_end_time
    state: unknown
then: []
else:
  - service: pod_point.charge_now
    data:
      seconds: 5
`

**Additional context**

-

**Comment by mattrayner** [comment]
Hi, thanks so much for raising this, I will look to release this in the next update to the plugin.

This should be sometime in the next week or so.

First I will update the podpointclient to support this
Then I'll implement it in the home assistant plugin

**Comment by busywait** [comment]
> Hi, thanks so much for raising this, I will look to release this in the next update to the plugin.
 
Thanks for this really helpful integration :)
