### ISSUE TITLE
Expose a "Charged" status like the PodPoint app does

### ISSUE THREAD

**Issue by busywait** [mattrayner/pod-point-home-assistant-component#51]
**Is your feature request related to a problem? Please describe.**
I'd like to set the colour of a lamp inside my house to show when my Pod Point is actually delivering power.

**Describe the solution you'd like**
Mirror the current Pod Point app and show a status change from Charging to Charged.

**Describe alternatives you've considered**
Using the status from my car, but it is not sent reliably - I'd rather be polling the mains powered PodPoint.

**Additional context**
I've seen that you have [considered this feature before](https://github.com/mattrayner/pod-point-home-assistant-component/issues/24#issuecomment-1465845002), but seeing it in the Pod Point app, perhaps the API reports this state now?

Charged
Your battery is charged or there is a charge schedule set on your vehicle.

PodPoint app Screenshot:
![Screenshot_20240331_173758_Pod Point](https://github.com/mattrayner/pod-point-home-assistant-component/assets/3671165/fcc6e341-9483-4841-bac3-9d9beb4f98cd)

**Comment by mattrayner** [comment]
Hi, so the API hasn't changed in this regard, it appears that they are using the same logic as proposed [here](https://github.com/mattrayner/pod-point-home-assistant-component/issues/24#issuecomment-1465845002) where we take a guess based on if the delivered charge number increases over time.

I will take a look at this again, but as the integration polls at a 5 minute interval, and doesn't directly store historical data (that is handled transparently by Home Assistant) its non-trivial to do reliably.

I previously had something implemented to do this but found that it introduced a number of bugs. I'll leave the issue open until its either implemented, or there is someone else that wants to take a crack at it :)

**Comment by mattrayner** [comment]
Interestingly, I have found a new status in a new api endpoint `/connectivity-status`

```
    "connectors": [{
      "id": 1,
      "door": "A",
      "chargingState": "SUSPENDED_EV"
    }],
```

`SUSPENDED_EV` *_could_* indicate the 'charged' status, I will be investigating further

**Comment by busywait** [comment]
It's consistent with the text in the Pod Point app:

> Charged
> Your battery is charged or there is a charge schedule set on your vehicle.

In my case I actually got into that state because the car reached the battery charge percentage limit.
