### ISSUE TITLE
Schedule Reset

### ISSUE THREAD

**Issue by eximo84** [mattrayner/pod-point-home-assistant-component#6]
## Version of the custom_component

Latest

## Configuration

```yaml

Add your logs here.

```

## Describe the bug

I have a schedule to run charging at the cheapest times. 00:30 - 06:30. I noticed it I toggle the charging allowed switch to ON the schedule is disabled in the pod point app. When the switch is OFF the schedule is enabled however my custom times are also reset to 00:00 which means charging doesn't happen at all. 

Is there a way to restore my settings and just toggle the schedule on/off?

## Debug log

```text

Add your logs here.

```

**Comment by danielsmith89** [comment]
This is how the custom component works.

Charging enabled: turns off any scheduling on the Podpoint which means charge always

Charging turned off: adds a schedule for each day between 00:00:00 and 00:00:01 which means basically it's off all the time.

You then don't use the schedules in the Podpoint app as everything is done with the custom component instead. The behaviour you are seeing is exactly as expected.

**Comment by eximo84** [comment]
Ah makes sense. Thank for clarifying.
