### ISSUE TITLE
Support solo 3s images

### ISSUE THREAD

**Issue by munaaf** [mattrayner/pod-point-home-assistant-component#64]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

The automation uses solo, or solo 3 logos, it would be good if both the entity cards, and entity images, set the logo based on the model, including solo 3s support. 
I have figured how I can add a new image in static subfolder, but I'm struggling to understand how to change the pod point status entity image which is always using the solo 2

**Describe the solution you'd like**

Configure pod point status image to support solo 3s universal or tethered

**Describe alternatives you've considered**

**Additional context**

![Screenshot_20240916-031053_Home Assistant](https://github.com/user-attachments/assets/12694368-9bf7-43dc-8346-93c45cc1c79d)

**Comment by munaaf** [comment]
I figured out it's in entity.py

It seems for my solo 3s UC the model is
S7-UC-05xxx

So 05 seems to be model id for the solo 3s

I think we can just add an 05 condition in the if, and add a png file for the solo 3s called uc-05.png

**Comment by mattrayner** [comment]
@munaaf if you want to open a pull request with the changes I'd happily accept it :)

**Comment by munaaf** [comment]
https://github.com/munaaf/pod-point-home-assistant-component/tree/munaaf-solo3s here you go!

**Comment by munaaf** [comment]
The readme with table of images needs updating, and the which_pod.png ideally updated to include Solo 3S image, I'm a bit weak on photo editing, so will leave that as optional for you to adjust :)

**Comment by mattrayner** [comment]
This update will be rolled into 2.0.6 that I will release shortly
