### ISSUE TITLE
Install on Home assistant 2022.8.7

### ISSUE THREAD

**Issue by Marky0** [mattrayner/pod-point-home-assistant-component#7]
I am new to HA and this is likely a duffer question, but it might be worth updating the readme for the newbee's !

Github readme says

_"Once you have installed either manually or via HACS, restart your home assistant instance and then setup the component by choosing **'Add integration' and search for 'Pod Point'** "_

I've installed through HACS and 'Pod Point' is available in the HACS/Integrations/Pod Point as shown in the screenshot.
But I am stuck on the next step in bold ? Where do I 'Add integration' ?
I can't find anything in 'Developer Tools' or 'Settings' menu that reference Pod Point.

I'm running HA on Virtual Box with the latest HA version
Home Assistant 2022.8.7
Supervisor 2022.08.3
Operating System 8.5
Frontend 20220802.0 - latest

![pod point](https://user-images.githubusercontent.com/4273841/187179492-1a288ca3-1f83-4d47-bfad-b93b775adb4c.jpg)

**Comment by danielsmith89** [comment]
I assume you've restarted Home Assistant since installing the PodPoint plugin from HACS?

**Comment by gangemij** [comment]
Yes several times. Did a reboot in the developer section and also a host reboot in the system section. It is not showing anywhere and I am unable to configure.

**Comment by gangemij** [comment]
I just remembered that you need to restart your GUI session on HA for it to show up when it is a custom component. So I opened a new browser and it showed up. Problem solved. @Marky0

**Comment by Marky0** [comment]
I've tried everything. Powered down my virtualbox HA. Logged out, back in again. Logged in in a new browser tab, Logged in in a new browser window.
Can I just check I should see pod point under
Settings/Integrations/Add Integration/Pod Point
screenshot below :
![Untitled](https://user-images.githubusercontent.com/4273841/187997837-8545de00-1ab1-4d63-90c4-67cac28bce84.jpg)

**Comment by mattrayner** [comment]
Hey @Marky0 apologies for the delay I've ben off with the kids for the end of the summer holidays. Are you able to check your file system inside the custom_components directory to ensure the component is there?


Additionally can you share your logs from the Settings/System/Logs section, it's possible there has been some error with initializing the component. If it fails to register for some reason this can prevent it from showing in the extension list.

Also, thanks to @gangemij and @danielsmith89 for jumping on this, the support is greatly appreciated :)

**Comment by Marky0** [comment]
Pod Point is in the custom_components directory and seems to be populated
![Untitled](https://user-images.githubusercontent.com/4273841/188002962-7d1556a9-2cdb-4f09-9ff2-9440f931c99e.jpg)

Log has the following error

2022-09-01 20:22:57.598 ERROR (SyncWorker_0) [homeassistant.loader] Error parsing manifest.json file at /config/custom_components/pod_point/manifest.json: input length is 0: line 1 column 2 (char 1)

**Comment by Marky0** [comment]
OK. Problem solved. Not sure what happened there. I examined the manifest.json file after the hint from the log file and found it was empty together will all the other *.py files in the pod_point directory. Re-downloaded Pod Point in HACs, rebooted and it has now appeared in 
Settings/Integrations/Add Integration/Pod Point
Thanks for you help !
Mark

**Comment by mattrayner** [comment]
The joy of HACS 😁. It's magic until it doesn't work, glad it's all sorted, I'll mark this as closed for now
